apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"

configMapGenerator:
  - name: grafana-dashboard-k8s-health-overview
    files:
      - k8s-health-overview.json=./dashboards/kubernetes/k8s-health-overview.json
